use Mix.Config

config :bubbleschat, Bubbleschat.Repo,
  username: "postgres",
  password: "+dbWUjah2XOGC3Z5qxiyWhH4NLKJxX+kIK9cmS8b+3nrLLsVpBijAHDyZxqdTs3Q",
  database: "postgres://gtwmnnuohxnddy:d2d5bddd042b274804ac73319c0403383199b62697fdb54882319e780c9f0a91@ec2-34-193-232-231.compute-1.amazonaws.com:5432/d65qs5652oenqk",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 18

# For production, don't forget to configure the url host
# to something meaningful, Phoenix uses this information
# when generating URLs.
#
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix phx.digest` task,
# which you should run after static files are built and
# before starting your production server.
config :bubbleschat, BubbleschatWeb.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [scheme: "https", host: "obscure-chamber-64399.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :bubbleschat, BubbleschatWeb.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [
#         port: 443,
#         cipher_suite: :strong,
#         keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#         certfile: System.get_env("SOME_APP_SSL_CERT_PATH"),
#         transport_options: [socket_opts: [:inet6]]
#       ]
#
# The `cipher_suite` is set to `:strong` to support only the
# latest and more secure SSL ciphers. This means old browsers
# and clients may not be supported. You can set it to
# `:compatible` for wider support.
#
# `:keyfile` and `:certfile` expect an absolute path to the key
# and cert in disk or a relative path inside priv, for example
# "priv/ssl/server.key". For all supported SSL configuration
# options, see https://hexdocs.pm/plug/Plug.SSL.html#configure/1
#
# We also recommend setting `force_ssl` in your endpoint, ensuring
# no data is ever sent via http, always redirecting to https:
#
#     config :bubbleschat, BubbleschatWeb.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# Finally import the config/prod.secret.exs which loads secrets
# and configuration from environment variables.
import_config "prod.secret.exs"
